version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo $WAIT_SIGNAL
      - |
        curl -X PUT $WAIT_SIGNAL \
        -H 'Content-Type: text/json' \
        -d @- << EOF

        {
          "Status" : "SUCCESS",
          "Reason" : "Configuration Complete",
          "UniqueId" : "SIGNALDONE",
          "Data" : "Application has completed configuration."
        }
        EOF
