version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo $WAIT_SIGNAL
      - |
        cat << EOF > success.json
        {
          "Status" : "SUCCESS",
          "Reason" : "Configuration Complete",
          "UniqueId" : "SIGNALDONE",
          "Data" : "Application has completed configuration."
        }

        EOF
      - curl -T success.json PUT "$WAIT_SIGNAL"
