version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo $WAIT_SIGNAL
      - echo $CODEBUILD_BUILD_ID
      - |
        curl -X PUT -H 'Content-Type:' --data-binary '{"Status" : "SUCCESS","Reason" : "Configuration Complete","UniqueId" : \"$CODEBUILD_BUILD_ID\","Data" : "Application is ready."}' "$WAIT_SIGNAL"
