version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - |
        curl -X PUT $WAIT_SIGNAL \
        -H 'Content-Type:' \
        --data-binary -@ <<EOF
        '{
            "Status" : "SUCCESS",
            "Reason" : "Configuration Complete",
            "UniqueId" : "ID",
            "Data" : "Application is ready."
        }'
        EOF
